version: '3.8'

services:
  audiobookshelf-sonos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiobookshelf-sonos
    environment:
      - SOAP_URI=
      - ABS_URI=
      - ABS_LIBRARY_ID=
      - ABS_TOKEN=
    ports:
      - 80:80
    volumes:
    - ./sonos.wsdl:/app/sonos.wsdl
